packages:
  - packages/*

pmOnFail: error
engineStrict: true
minimumReleaseAge: 43200
minimumReleaseAgeIgnoreMissingTime: false

catalog:
  camelcase: 8.0.0

catalogs:
  tooling:
    "@types/node": 26.2.0
    typescript: 5.9.3
