# Consumed API of the pinned semantic_version 2.10 package.
# Chainman constructs complete versions from strings; partial versions and the
# library's other constructors are deliberately outside this local stub.
class Version:
    major: int
    minor: int
    patch: int
    prerelease: tuple[str, ...]
    build: tuple[str, ...]
    def __init__(self, version_string: str) -> None: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: Version) -> bool: ...
    def __le__(self, other: Version) -> bool: ...
    def __gt__(self, other: Version) -> bool: ...
    def __ge__(self, other: Version) -> bool: ...

class NpmSpec:
    def __init__(self, expression: str) -> None: ...
    def match(self, version: Version) -> bool: ...
    def __contains__(self, version: object) -> bool: ...
