"""The opinionated public recipe facade; project differences are declarations."""

import argparse
from pathlib import Path
import re
import shlex
import tomllib

import toolchain as tc


FILE = "scripts/chainman.just"
BINDINGS = {
    "setup",
    "generate",
    "format-write",
    "format-check",
    "format-staged",
    "format-hygiene",
    "verify",
    "verify-lite",
    "doctor",
    "clean",
}
BUILTINS = {
    "exec": ["exec", "--"],
    "shell": ["shell"],
    "format": ["format"],
    "format-staged": ["format", "--staged"],
    "deps-update": ["deps-update"],
    "chainman-update": ["chainman-update"],
    "cache-status": ["cache-status"],
    "cache-prune": ["cache-prune"],
    "services-status": ["services-status"],
    "stop": ["services-stop"],
    "setup-status": ["setup-status"],
    "config": ["config"],
    "explain": ["explain"],
    "deps-check": ["deps-check"],
    "deps-coverage": ["deps-coverage"],
    "deps-policy-report": ["deps-policy-report"],
    "deps-audit": ["deps-audit"],
}


def bindings(cfg):
    result = cfg.get("recipes", {})
    if not isinstance(result, dict) or set(result) - BINDINGS:
        raise ValueError("Unknown standard recipe binding")
    for name, tasks in result.items():
        if not isinstance(tasks, list) or any(
            task not in cfg.get("tasks", {}) for task in tasks
        ):
            raise ValueError(f"Recipe {name} requires declared task names")
        if len(tasks) != len(set(tasks)):
            raise ValueError(f"Recipe {name} repeats a task")
    return result


def verification(cfg):
    declared = bindings(cfg).get("verify")
    updates = cfg.get("updates", {})
    selected = updates.get(
        "verify_tasks", [updates["verify_task"]] if "verify_task" in updates else []
    )
    if declared is not None and selected and declared != selected:
        raise ValueError(
            "Recipe verify and update verification must select the same gate"
        )
    return declared if declared is not None else selected


def render(cfg):
    declared = bindings(cfg)
    actions = {name: [argv] for name, argv in BUILTINS.items()}
    for name in BINDINGS - {"format-hygiene"}:
        tasks = verification(cfg) if name == "verify" else declared.get(name, [])
        if tasks:
            actions[name] = [["run", task] for task in tasks]
        elif name == "setup":
            actions[name] = [["setup"]]
        elif name == "format-staged":
            continue
        elif name in {
            "generate",
            "format-check",
            "format-write",
            "format-staged",
            "verify",
            "verify-lite",
        }:
            actions[name] = [["_recipe-required", name]]
    actions["doctor"] = [["doctor"], *actions.get("doctor", [])]
    actions["clean"] = [["services-stop"], *actions.get("clean", []), ["clean"]]
    for target in sorted(
        set(cfg.get("updates", {}).get("adapters", {}))
        | set(cfg.get("updates", {}).get("target_groups", {}))
    ):
        if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]*", target):
            actions["deps-update-" + target] = [["deps-update", "targets=" + target]]
    lines = [
        "# Generated by the pinned Chainman runtime. Configure recipes in chainman.toml.",
        "",
    ]
    for name, commands in sorted(actions.items()):
        lines += [
            '[group("Chainman")]',
            "[positional-arguments]",
            f"{name} *args:",
            "    #!/bin/sh",
            "    set -eu",
        ]
        for index, command in enumerate(commands):
            prefix = "exec " if index == len(commands) - 1 else ""
            extra = ' "$@"' if index == len(commands) - 1 else ""
            lines.append(
                "    " + prefix + "./scripts/chainman.sh " + shlex.join(command) + extra
            )
        lines.append("")
    return "\n".join(lines).encode()


def sync(root, *, check=False):
    body = render(config(root))
    path = tc.contained(root, FILE)
    if check:
        if tc.regular_input(root, FILE) != body:
            raise ValueError(
                "Standard recipe facade differs from its declared configuration"
            )
    else:
        tc.atomic_bytes(path, body, 0o644)


def roots(root):
    cfg = tc.config(root)
    return [
        path
        for path in [
            root,
            *[
                tc.contained(root, name)
                for name in cfg.get("runtime", {}).get("copies", [])
            ],
        ]
        if ((path / "chainman.toml").is_file() or (path / "chainman.toml.j2").is_file())
        and "recipes" in config(path)
    ]


def config(root):
    if (root / "chainman.toml").is_file():
        return tc.config(root)
    # Templates keep recipe declarations valid TOML; quoted placeholders may
    # appear in unrelated fields such as the project name.
    import configuration

    return configuration.compile(
        tomllib.loads(tc.regular_input(root, "chainman.toml.j2").decode())
    )[0]


def options(arguments):
    """Normalize public options without interpreting values as options or code."""
    main, resolver = [], []
    pending = None
    selected: dict[str, int] = {}
    passthrough = False
    for argument in arguments:
        if pending is not None:
            pending.append(argument)
            pending = None
            continue
        if passthrough:
            resolver.append(argument)
            continue
        if argument == "--":
            passthrough = True
            continue
        if argument in {"--targets", "--policy", "--target-policy"}:
            resolver.append(argument)
            pending = resolver
            continue
        if argument == "--message":
            main.append(argument)
            pending = main
            continue
        key, separator, value = argument.partition("=")
        if not separator:
            main.append(argument)
        elif key in {"--targets", "--policy", "--target-policy"}:
            resolver.append(argument)
        elif key == "--message":
            main.append(argument)
        elif key == "commit" and value in {"auto", "off"}:
            if key in selected:
                main[selected[key]] = None
            selected[key] = len(main)
            main.append("--no-commit" if value == "off" else None)
        elif key == "mode" and value in {"apply", "dry-run"}:
            if key in selected:
                main[selected[key]] = None
            selected[key] = len(main)
            main.append("--preview" if value == "dry-run" else None)
        elif key in {"targets", "policy"}:
            resolver += ["--" + key, value]
        elif key.endswith("_policy") and re.fullmatch(
            r"[A-Za-z0-9][A-Za-z0-9_-]*", key[:-7]
        ):
            resolver += ["--target-policy", key[:-7] + "=" + value]
        elif key == "message":
            main += ["--message", value]
        else:
            raise ValueError(f"Unsupported recipe option: {key}")
    if pending is not None:
        raise ValueError("Option requires a value")
    return [item for item in main if item is not None] + (
        ["--", *resolver] if resolver else []
    )


def selection_options(arguments):
    normalized = options(arguments)
    if normalized[:1] == ["--"]:
        return normalized[1:]
    if normalized:
        raise ValueError("Inspection accepts targets and policy options only")
    return []


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--render", action="store_true")
    args = parser.parse_args()
    if args.render:
        import sys

        sys.stdout.buffer.write(render(config(args.root)))
    else:
        sync(args.root, check=args.check)
